version: '3'
services:
  app:
    container_name: drivent
    build: .
    ports:
      - 5000:4000
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file: 
          - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: